export const MegalodonSignal = Object.freeze({
  WORKFLOW_C2_EXFIL: 'D1_WORKFLOW_C2_EXFIL',
  WORKFLOW_DECODE_CHAIN: 'D1_WORKFLOW_DECODE_CHAIN',
  CREDENTIAL_HARVEST: 'D2_CREDENTIAL_HARVEST',
  PUBLISH_VELOCITY: 'D3_PUBLISH_VELOCITY',
  PUBLISHER_DRIFT: 'D4_PUBLISHER_DRIFT',
  BOT_COMMIT_IDENTITY: 'D5_BOT_COMMIT_IDENTITY',
  DATE_ANACHRONISM: 'D6_DATE_ANACHRONISM',
});
